# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bantic-rightscale-api}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Michael", "Cory Forsyth"]
  s.date = %q{2010-07-13}
  s.description = %q{A Ruby Wrapper for the RightScale API}
  s.email = %q{cory.forsyth@gmail.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "README.markdown",
     "Rakefile",
     "VERSION",
     "bantic-rightscale-api.gemspec",
     "lib/bantic-rightscale-api.rb",
     "lib/rightscale/api.rb",
     "lib/rightscale/client.rb",
     "lib/rightscale/deployments.rb",
     "lib/rightscale/right_scripts.rb",
     "lib/rightscale/server_arrays.rb",
     "lib/rightscale/servers.rb",
     "lib/rightscale/statuses.rb",
     "lib/support/hash_with_indifferent_access.rb",
     "pkg/bantic-rightscale-api-0.3.0.gem"
  ]
  s.homepage = %q{http://github.com/bantic/rightscale-api}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A Ruby Wrapper for the RightScale API}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0"])
    else
      s.add_dependency(%q<httparty>, [">= 0"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0"])
  end
end

